services:
  batch:
    build: .
    ports:
      - "8080:8080"
    networks:
      - local
    depends_on:
      redis:
        condition: service_started
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - local

networks:
  local:
    driver: bridge
