spring:
  application:
    name: @project.name@
  data:
    mongodb:
      host: mongodb # Refers to the docker-compose service of the same name
      port: 27017
      database: prices
    redis:
      host: redis # Refers to the docker-compose service of the same name
      port: 6379

ge-prices:
  base-url: prices.runescape.wiki/api/v1/osrs
  item-mapping-url: /mapping
  five-minute-prices-url: /5m

largest-response-size-kb: 800

logging:
  level:
    com.github.benwarc.osrsgepricesbatch: DEBUG
